In [31]:
import pandas as pd

db= pd.read_csv("../data/01_raw/pokemon_library_images/pokemonDB_dataset.csv")
pokedex = pd.read_csv("../data/01_raw/pokemon_sprites_csv/pokemon_images/pokedex.csv")

In [32]:
db.head()

,Pokemon,Type,Species,Height,Weight,Abilities,EV Yield,Catch Rate,Base Friendship,Base Exp,...,Defense Max,Special Attack Base,Special Attack Min,Special Attack Max,Special Defense Base,Special Defense Min,Special Defense Max,Speed Base,Speed Min,Speed Max
0,Abomasnow,"Grass, Ice",Frost Tree Pokémon,2.2 m (7′03″),135.5 kg (298.7 lbs),"1. Snow Warning, Soundproof (hidden ability)","1 Attack, 1 Sp. Atk","60 (7.8% with PokéBall, full HP)",50 (normal),173,...,273,92,170,311,85,157,295,60,112,240
1,Mega Abomasnow,"Grass, Ice",Frost Tree Pokémon,2.7 m (8′10″),185.0 kg (407.9 lbs),1. Snow Warning,"1 Attack, 1 Sp. Atk","60 (7.8% with PokéBall, full HP)",50 (normal),208,...,339,132,242,399,105,193,339,30,58,174
2,Abra,Psychic,Psi Pokémon,0.9 m (2′11″),19.5 kg (43.0 lbs),"1. Synchronize, 2. Inner Focus, Magic Guard (h...",1 Sp. Atk,"200 (26.1% with PokéBall, full HP)",50 (normal),62,...,141,105,193,339,55,103,229,90,166,306
3,Absol,Dark,Disaster Pokémon,1.2 m (3′11″),47.0 kg (103.6 lbs),"1. Pressure, 2. Super Luck, Justified (hidden ...",2 Attack,"30 (3.9% with PokéBall, full HP)",35 (lower than normal),163,...,240,75,139,273,60,112,240,75,139,273
4,Mega Absol,Dark,Disaster Pokémon,1.2 m (3′11″),49.0 kg (108.0 lbs),1. Magic Bounce,2 Attack,"30 (3.9% with PokéBall, full HP)",35 (lower than normal),198,...,240,115,211,361,60,112,240,115,211,361

In [33]:
pokedex.head()

,id,name,pokedex_id,type1,type2,primary_color,shape,legendary,mega_evolution,alolan_form,galarian_form,gigantamax,image_fn
0,0,Bulbasaur,1,Grass,Poison,Green,Quadruped,False,False,False,False,False,['1']
1,1,Ivysaur,2,Grass,Poison,Green,Quadruped,False,False,False,False,False,['2']
2,2,Venusaur,3,Grass,Poison,Green,Quadruped,False,False,False,False,False,['3']
3,3,Venusaur Gmax,3,Grass,Poison,Green,Quadruped,False,False,False,False,True,['3_g']
4,4,Venusaur Mega,3,Grass,Poison,Green,Quadruped,False,True,False,False,False,['3_2']

In [34]:
print(len(db), len(pokedex))

1215 1118

In [ ]:
def normalize_names(pokedex: pd.DataFrame, db: pd.DataFrame):
    pokedex["_name"] = pokedex["name"].str.strip().str.lower()
    db["_name"] = (
    db["Pokemon"]
        .str.strip()
        .str.lower()
        .str.replace(r"\s+forme$", "", regex=True)   
        .str.replace(r"%", "", regex=False)          
        .str.strip()
    )

    return pokedex, db


normalize_names(pokedex,)

(        id                  name  pokedex_id    type1   type2 primary_color  \
 0        0             Bulbasaur           1    Grass  Poison         Green
 1        1               Ivysaur           2    Grass  Poison         Green
 2        2              Venusaur           3    Grass  Poison         Green
 3        3         Venusaur Gmax           3    Grass  Poison         Green
 4        4         Venusaur Mega           3    Grass  Poison         Green
 ...    ...                   ...         ...      ...     ...           ...
 1113  1113             Glastrier         896      Ice     NaN         White
 1114  1114             Spectrier         897    Ghost     NaN         Black
 1115  1115               Calyrex         898  Psychic   Grass         Green
 1116  1116     Calyrex Ice Rider         898  Psychic     Ice         Green
 1117  1117  Calyrex Shadow Rider         898  Psychic   Ghost         Green

           shape  legendary  mega_evolution  alolan_form  galarian_form  \
 0     Quadruped      False           False        False          False
 1     Quadruped      False           False        False          False
 2     Quadruped      False           False        False          False
 3     Quadruped      False           False        False          False
 4     Quadruped      False            True        False          False
 ...         ...        ...             ...          ...            ...
 1113  Quadruped       True           False        False          False
 1114  Quadruped       True           False        False          False
 1115   Humanoid       True           False        False          False
 1116   Humanoid       True           False        False          False
 1117   Humanoid       True           False        False          False

       gigantamax   image_fn                 _name
 0          False      ['1']             bulbasaur
 1          False      ['2']               ivysaur
 2          False      ['3']              venusaur
 3           True    ['3_g']         venusaur gmax
 4          False    ['3_2']         venusaur mega
 ...          ...        ...                   ...
 1113       False    ['896']             glastrier
 1114       False    ['897']             spectrier
 1115       False  ['898_1']               calyrex
 1116       False  ['898_2']     calyrex ice rider
 1117       False  ['898_3']  calyrex shadow rider

 [1118 rows x 14 columns],
                      Pokemon            Type             Species  \
 0                  Abomasnow      Grass, Ice  Frost Tree Pokémon
 1             Mega Abomasnow      Grass, Ice  Frost Tree Pokémon
 2                       Abra         Psychic         Psi Pokémon
 3                      Absol            Dark    Disaster Pokémon
 4                 Mega Absol            Dark    Disaster Pokémon
 ...                      ...             ...                 ...
 1210                   Zubat  Poison, Flying         Bat Pokémon
 1211                Zweilous    Dark, Dragon     Hostile Pokémon
 1212       Zygarde 50% Forme  Dragon, Ground       Order Pokémon
 1213       Zygarde 10% Forme  Dragon, Ground       Order Pokémon
 1214  Zygarde Complete Forme  Dragon, Ground       Order Pokémon

               Height                 Weight  \
 0      2.2 m (7′03″)   135.5 kg (298.7 lbs)
 1      2.7 m (8′10″)   185.0 kg (407.9 lbs)
 2      0.9 m (2′11″)     19.5 kg (43.0 lbs)
 3      1.2 m (3′11″)    47.0 kg (103.6 lbs)
 4      1.2 m (3′11″)    49.0 kg (108.0 lbs)
 ...              ...                    ...
 1210   0.8 m (2′07″)      7.5 kg (16.5 lbs)
 1211   1.4 m (4′07″)    50.0 kg (110.2 lbs)
 1212  5.0 m (16′05″)   305.0 kg (672.4 lbs)
 1213   1.2 m (3′11″)     33.5 kg (73.9 lbs)
 1214  4.5 m (14′09″)  610.0 kg (1344.8 lbs)

                                               Abilities             EV Yield  \
 0          1. Snow Warning, Soundproof (hidden ability)  1 Attack, 1 Sp. Atk
 1                                       1. Snow Warning  1 Attack, 1 Sp. Atk
 2     1. Synchronize, 2. Inner Focus, Magic Guard (h...            1 Sp. Atk
 3     1. Pressure, 2. Super Luck, Justified (hidden ...             2 Attack
 4                                       1. Magic Bounce             2 Attack
 ...                                                 ...                  ...
 1210       1. Inner Focus, Infiltrator (hidden ability)              1 Speed
 1211                                          1. Hustle             2 Attack
 1212                  1. Aura Break, 2. Power Construct                 3 HP
 1213                  1. Aura Break, 2. Power Construct                 3 HP
 1214                                 1. Power Construct                 3 HP

                               Catch Rate         Base Friendship Base Exp  \
 0       60 (7.8% with PokéBall, full HP)             50 (normal)      173
 1       60 (7.8% with PokéBall, full HP)             50 (normal)      208
 2     200 (26.1% with PokéBall, full HP)             50 (normal)       62
 3       30 (3.9% with PokéBall, full HP)  35 (lower than normal)      163
 4       30 (3.9% with PokéBall, full HP)  35 (lower than normal)      198
 ...                                  ...                     ...      ...
 1210  255 (33.3% with PokéBall, full HP)             50 (normal)       49
 1211    45 (5.9% with PokéBall, full HP)  35 (lower than normal)      147
 1212     3 (0.4% with PokéBall, full HP)   0 (lower than normal)      270
 1213     3 (0.4% with PokéBall, full HP)   0 (lower than normal)      219
 1214     3 (0.4% with PokéBall, full HP)   0 (lower than normal)      319

       ... Special Attack Base Special Attack Min Special Attack Max  \
 0     ...                  92                170                311
 1     ...                 132                242                399
 2     ...                 105                193                339
 3     ...                  75                139                273
 4     ...                 115                211                361
 ...   ...                 ...                ...                ...
 1210  ...                  30                 58                174
 1211  ...                  65                121                251
 1212  ...                  81                150                287
 1213  ...                  61                114                243
 1214  ...                  91                168                309

      Special Defense Base  Special Defense Min  Special Defense Max  \
 0                      85                  157                  295
 1                     105                  193                  339
 2                      55                  103                  229
 3                      60                  112                  240
 4                      60                  112                  240
 ...                   ...                  ...                  ...
 1210                   40                   76                  196
 1211                   70                  130                  262
 1212                   95                  175                  317
 1213                   85                  157                  295
 1214                   95                  175                  317

       Speed Base  Speed Min  Speed Max             _name
 0             60        112        240         abomasnow
 1             30         58        174    mega abomasnow
 2             90        166        306              abra
 3             75        139        273             absol
 4            115        211        361        mega absol
 ...          ...        ...        ...               ...
 1210          55        103        229             zubat
 1211          58        108        236          zweilous
 1212          95        175        317        zygarde 50
 1213         115        211        361        zygarde 10
 1214          85        157        295  zygarde complete

 [1215 rows x 33 columns])

In [41]:
def left_merge(pokedex, db):
    merged = db.merge(pokedex, on="_name", how="left")
    return merged

merged = left_merge(pokedex, db)
matched = set(merged["_name"])
pokedex_unmatched = set(pokedex["_name"]) - matched

pokedex_unmatched

{'abomasnow mega',
 'absol mega',
 'aerodactyl mega',
 'aggron mega',
 'alakazam mega',
 'alcremie gmax',
 'altaria mega',
 'ampharos mega',
 'appletun gmax',
 'araquanid totem',
 'articuno galar',
 'audino mega',
 'banette mega',
 'basculin blue striped',
 'basculin red striped',
 'beedrill mega',
 'blastoise gmax',
 'blastoise mega',
 'blaziken mega',
 'burmy',
 'butterfree gmax',
 'camerupt mega',
 'castform rainy',
 'castform snowy',
 'castform sunny',
 'centiskorch gmax',
 'charizard gmax',
 'charizard mega x',
 'charizard mega y',
 'cinderace gmax',
 'coalossal gmax',
 'copperajah gmax',
 'corsola galar',
 'corviknight gmax',
 'darmanitan standard',
 'darmanitan standard galar',
 'darmanitan zen',
 'darmanitan zen galar',
 'darumaka galar',
 'diancie mega',
 'diglett alola',
 'drednaw gmax',
 'dugtrio alola',
 'duraludon gmax',
 'eevee gmax',
 'eiscue ice',
 'eiscue noice',
 'exeggutor alola',
 'farfetchd',
 'farfetchd galar',
 'flabebe',
 'flapple gmax',
 'floette eternal',
 'gallade mega',
 'garbodor gmax',
 'garchomp mega',
 'gardevoir mega',
 'gengar gmax',
 'gengar mega',
 'geodude alola',
 'glalie mega',
 'golem alola',
 'gourgeist average',
 'gourgeist large',
 'gourgeist small',
 'gourgeist super',
 'graveler alola',
 'greninja ash',
 'greninja battle bond',
 'grimer alola',
 'grimmsnarl gmax',
 'groudon primal',
 'gumshoos totem',
 'gyarados mega',
 'hakamo o',
 'hatterene gmax',
 'heracross mega',
 'ho oh',
 'hoopa',
 'houndoom mega',
 'inteleon gmax',
 'jangmo o',
 'kangaskhan mega',
 'keldeo ordinary',
 'keldeo resolute',
 'kingler gmax',
 'kommo o',
 'kommo o totem',
 'kyogre primal',
 'kyurem black',
 'kyurem white',
 'lapras gmax',
 'latias mega',
 'latios mega',
 'linoone galar',
 'lopunny mega',
 'lucario mega',
 'lurantis totem',
 'lycanroc dusk',
 'lycanroc midday',
 'lycanroc midnight',
 'machamp gmax',
 'magearna original',
 'manectric mega',
 'marowak alola',
 'marowak totem',
 'mawile mega',
 'medicham mega',
 'melmetal gmax',
 'meowth alola',
 'meowth galar',
 'meowth gmax',
 'metagross mega',
 'mewtwo mega x',
 'mewtwo mega y',
 'mime jr',
 'mimikyu busted',
 'mimikyu disguised',
 'mimikyu totem busted',
 'mimikyu totem disguised',
 'minior blue',
 'minior blue meteor',
 'minior green',
 'minior green meteor',
 'minior indigo',
 'minior indigo meteor',
 'minior orange',
 'minior orange meteor',
 'minior red',
 'minior red meteor',
 'minior violet',
 'minior violet meteor',
 'minior yellow',
 'minior yellow meteor',
 'moltres galar',
 'morpeko',
 'mr mime',
 'mr mime galar',
 'mr rime',
 'muk alola',
 'necrozma dawn',
 'necrozma dusk',
 'necrozma ultra',
 'nidoran f',
 'nidoran m',
 'ninetales alola',
 'orbeetle gmax',
 'oricorio baile',
 'oricorio pau',
 'oricorio pom pom',
 'oricorio sensu',
 'persian alola',
 'pidgeot mega',
 'pikachu alola cap',
 'pikachu belle',
 'pikachu cosplay',
 'pikachu gmax',
 'pikachu hoenn cap',
 'pikachu kalos cap',
 'pikachu libre',
 'pikachu original cap',
 'pikachu partner cap',
 'pikachu phd',
 'pikachu pop star',
 'pikachu rock star',
 'pikachu sinnoh cap',
 'pikachu unova cap',
 'pinsir mega',
 'ponyta galar',
 'porygon z',
 'pumpkaboo average',
 'pumpkaboo large',
 'pumpkaboo small',
 'pumpkaboo super',
 'raichu alola',
 'rapidash galar',
 'raticate alola',
 'raticate totem alola',
 'rattata alola',
 'rayquaza mega',
 'ribombee totem',
 'rillaboom gmax',
 'rockruff own tempo',
 'rotom fan',
 'rotom frost',
 'rotom heat',
 'rotom mow',
 'rotom wash',
 'sableye mega',
 'salamence mega',
 'salazzle totem',
 'sandaconda gmax',
 'sandshrew alola',
 'sandslash alola',
 'sceptile mega',
 'scizor mega',
 'sharpedo mega',
 'sirfetchd',
 'slowbro galar',
 'slowbro mega',
 'slowking galar',
 'slowpoke galar',
 'snorlax gmax',
 'steelix mega',
 'stunfisk galar',
 'swampert mega',
 'togedemaru totem',
 'toxtricity amped',
 'toxtricity amped gmax',
 'toxtricity low key',
 'toxtricity low key gmax',
 'type null',
 'tyranitar mega',
 'urshifu rapid strike',
 'urshifu rapid strike gmax',
 'urshifu single strike',
 'urshifu single strike gmax',
 'venusaur gmax',
 'venusaur mega',
 'vikavolt totem',
 'vulpix alola',
 'weezing galar',
 'wishiwashi school',
 'wishiwashi solo',
 'wormadam plant',
 'wormadam sandy',
 'wormadam trash',
 'yamask galar',
 'zacian crowned',
 'zacian hero',
 'zamazenta crowned',
 'zamazenta hero',
 'zapdos galar',
 'zigzagoon galar',
 'zygarde'}

In [44]:
merged.columns

Index(['Pokemon', 'Type', 'Species', 'Height', 'Weight', 'Abilities',
       'EV Yield', 'Catch Rate', 'Base Friendship', 'Base Exp', 'Growth Rate',
       'Egg Groups', 'Gender', 'Egg Cycles', 'HP Base', 'HP Min', 'HP Max',
       'Attack Base', 'Attack Min', 'Attack Max', 'Defense Base',
       'Defense Min', 'Defense Max', 'Special Attack Base',
       'Special Attack Min', 'Special Attack Max', 'Special Defense Base',
       'Special Defense Min', 'Special Defense Max', 'Speed Base', 'Speed Min',
       'Speed Max', '_name', 'id', 'name', 'pokedex_id', 'type1', 'type2',
       'primary_color', 'shape', 'legendary', 'mega_evolution', 'alolan_form',
       'galarian_form', 'gigantamax', 'image_fn'],
      dtype='object')

In [50]:
to_drop = ["Type", "Species", "Abilities", "EV Yield", "id", "pokedex_id", "image_fn", "Pokemon"]
merged = merged.drop(columns=to_drop, errors="ignore")

merged.head()

,Height,Weight,Catch Rate,Base Friendship,Base Exp,Growth Rate,Egg Groups,Gender,Egg Cycles,HP Base,...,name,type1,type2,primary_color,shape,legendary,mega_evolution,alolan_form,galarian_form,gigantamax
0,2.2 m (7′03″),135.5 kg (298.7 lbs),"60 (7.8% with PokéBall, full HP)",50 (normal),173,Slow,"Grass, Monster","50% male, 50% female","20 (4,884–5,140 steps)",90,...,Abomasnow,Grass,Ice,White,Upright,False,False,False,False,False
1,2.7 m (8′10″),185.0 kg (407.9 lbs),"60 (7.8% with PokéBall, full HP)",50 (normal),208,Slow,"Grass, Monster","50% male, 50% female","20 (4,884–5,140 steps)",90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.9 m (2′11″),19.5 kg (43.0 lbs),"200 (26.1% with PokéBall, full HP)",50 (normal),62,Medium Slow,Human-Like,"75% male, 25% female","20 (4,884–5,140 steps)",25,...,Abra,Psychic,NaN,Brown,Upright,False,False,False,False,False
3,1.2 m (3′11″),47.0 kg (103.6 lbs),"30 (3.9% with PokéBall, full HP)",35 (lower than normal),163,Medium Slow,Field,"50% male, 50% female","25 (6,169–6,425 steps)",65,...,Absol,Dark,NaN,White,Quadruped,False,False,False,False,False
4,1.2 m (3′11″),49.0 kg (108.0 lbs),"30 (3.9% with PokéBall, full HP)",35 (lower than normal),198,Medium Slow,Field,"50% male, 50% female","25 (6,169–6,425 steps)",65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
!pip install rapidfuzz

Requirement already satisfied: rapidfuzz in /usr/local/lib/python3.12/dist-packages (3.14.5)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [60]:
import re

def clean_pokemon_name(name):
    if pd.isna(name):
        return ""
    
    name = str(name).lower()
    
    stopwords = [
        'mega', 'galarian', 'alolan', 'hisuian', 'paldean', 
        'standard', 'mode', 'zen', 'normal', 'attack', 'defense', 
        'origin', 'therian', 'crowned', 'shield', 'sword', 'form', 'forme',
        'two-segment', 'ice face', 'zen mode', 'gigantamax'
    ]
    
    pattern = r'\b(' + '|'.join(stopwords) + r')\b'
    name = re.sub(pattern, '', name)
    
    name = re.sub(r'[^a-z0-9]', ' ', name) 
    name = ' '.join(name.split())
    
    return name

In [61]:
import numpy as np
from rapidfuzz import process, fuzz

temp = merged.copy()
temp['_name_clean'] = temp['_name'].apply(clean_pokemon_name)

ref_df = temp.dropna(subset=['name', 'type1', 'primary_color', 'shape']).copy()

target_mask = temp[['type1', 'primary_color', 'shape']].isnull().any(axis=1)
target_indices = temp[target_mask].index

ref_names = ref_df['name'].tolist()

for idx in target_indices:
    query_name = str(temp.at[idx, '_name_clean'])
    
    match = process.extractOne(
        query_name, 
        ref_names, 
        scorer=fuzz.token_sort_ratio
    )
    
    if match:
        best_name, score, _ = match
        
        words_query = set(query_name.lower().split())
        words_best = set(best_name.lower().split())
        has_overlap = not words_query.isdisjoint(words_best)
        
        if score >= 30 or has_overlap:
            source_row = ref_df[ref_df['name'] == best_name].iloc[0]
            
            temp.at[idx, 'name'] = source_row['name']
            temp.at[idx, 'type1'] = source_row['type1']
            temp.at[idx, 'primary_color'] = source_row['primary_color']
            temp.at[idx, 'shape'] = source_row['shape']

print(temp.loc[target_indices, ['_name_clean', 'name', 'type1']])

     _name_clean        name     type1
1      abomasnow   Abomasnow     Grass
4          absol       Absol      Dark
9     aerodactyl  Aerodactyl      Rock
11        aggron      Aggron     Steel
14      alakazam    Alakazam   Psychic
...          ...         ...       ...
1196   zamazenta     Lampent     Ghost
1199      zapdos      Zapdos  Electric
1205   zigzagoon   Zigzagoon    Normal
1207     zoroark     Zoroark      Dark
1209       zorua       Zorua      Dark

[332 rows x 3 columns]

In [62]:
print(temp[['name', 'type1', 'primary_color', 'shape']].isnull().sum())

name             0
type1            0
primary_color    0
shape            0
dtype: int64

In [63]:
temp.to_csv("merged2.csv")

In [65]:
temp.columns

Index(['Height', 'Weight', 'Catch Rate', 'Base Friendship', 'Base Exp',
       'Growth Rate', 'Egg Groups', 'Gender', 'Egg Cycles', 'HP Base',
       'HP Min', 'HP Max', 'Attack Base', 'Attack Min', 'Attack Max',
       'Defense Base', 'Defense Min', 'Defense Max', 'Special Attack Base',
       'Special Attack Min', 'Special Attack Max', 'Special Defense Base',
       'Special Defense Min', 'Special Defense Max', 'Speed Base', 'Speed Min',
       'Speed Max', '_name', 'name', 'type1', 'type2', 'primary_color',
       'shape', 'legendary', 'mega_evolution', 'alolan_form', 'galarian_form',
       'gigantamax', '_name_clean'],
      dtype='object')